### ISSUE TITLE
Download unavailable on X/Twitter

### ISSUE THREAD

**Issue by AndrewM014** [JunkFood02/Seal#1008]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Download unavailable on X/Twitter which used to be available.

### Error reports

App version: 1.10.0-beta.5 (10920)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

URL: https://twitter.com/ReignOfPride/status/1694567408139137066?t=NQr7THvXqSlZvr3TenrS7g&s=09
ERROR: [twitter] 1694567408139137066: No video could be found in this tweet

**Comment by solonovamax** [comment]
This issue is an issue with upstream yt-dlp, so seal can't do anything to fix it atm.

**Comment by ricecooka** [comment]
Had the same issue in yt-dlp, that was fixed with update to nightly release

**Comment by AndrewM014** [comment]
Still not working, the errors is as follows:-

App version: 1.9.2 (10920)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

URL: https://twitter.com/ItsNotMeek/status/1696175476358721569?t=kjH6Il0cumzhjNHwlbmXOg&s=09
ERROR: [twitter] 1696175476358721569: Unable to download JSON metadata: <urlopen error [Errno 7] No address associated with hostname> (caused by URLError(gaierror(7, 'No address associated with hostname')))

**Comment by Marco-9456** [comment]
You're not using nightly
