### ISSUE TITLE
Bilibili extraxtor error when using cookies 

### ISSUE THREAD

**Issue by Lolmerlin** [JunkFood02/Seal#1219]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Extractor error when using cookies please fix

### To Reproduce

1. Go to bilibili.com copy the link of the video
2. Go to seal app and paste it with cookies of a big member account (premium)
3. And there you go error 

### Error reports

WARNING: [generic] Falling back on generic information extractor
ERROR: Unsupported URL: https://m.bilibili.com/video/BV1Fo4y1t7yE?buvid=XUFB87BF204BF847DBBAF47F9B38A57ABF6CF&is_story_h5=false&mid=AIf%2BOfj39XNBzA4dJeuQhX8FTQ%2FSZMtL1rElX6M3iMo%3D&p=1&plat_id=168&share_from=ugc&share_medium=android_i&share_plat=android&share_session_id=ea9ac6e7-b08e-40bd-b917-b3f7331252b8&share_source=COPY&share_tag=s_i&spmid=main.my-history-search-result.option-more.0&timestamp=1702271235&unique_k=GLNjc5k&up_id=321181129&share_times=1

### Screenshots & Screen Records

![Screenshot_20231211_121509_Seal](https://github.com/JunkFood02/Seal/assets/153481800/bfbd0dfa-50b8-4157-8c82-8691a082caf1)

### Additional context

WARNING: [generic] Falling back on generic information extractor
ERROR: Unsupported URL: https://m.bilibili.com/video/BV1Fo4y1t7yE?buvid=XUFB87BF204BF847DBBAF47F9B38A57ABF6CF&is_story_h5=false&mid=AIf%2BOfj39XNBzA4dJeuQhX8FTQ%2FSZMtL1rElX6M3iMo%3D&p=1&plat_id=168&share_from=ugc&share_medium=android_i&share_plat=android&share_session_id=ea9ac6e7-b08e-40bd-b917-b3f7331252b8&share_source=COPY&share_tag=s_i&spmid=main.my-history-search-result.option-more.0&timestamp=1702271235&unique_k=GLNjc5k&up_id=321181129&share_times=1

**Comment by JunkFood02** [comment]
> The mobile web page and the mainframe web page of bilibili seem to use different video interfaces

Maybe some changes were made in bilibili's side. Can confirm that cookies with mobile webpage still works with resolutions available for free accounts (up to 1080p). I don't have a paid subscription so I can't verify if the issue can be reproduced on PC and yt-dlp.

**Comment by JunkFood02** [comment]
Furthermore, you can use a cookies.txt dumped from browser on your PC with Seal and see if it works

**Comment by Lolmerlin** [comment]
Oh ok

**Comment by JunkFood02** [comment]
Go to Settings - Network - Cookies, tap on the three dots icon on the top right and turn off `User agent` should work. The bug which causes this option to be enabled by accident was addressed in v1.11.2

**Comment by PYUDNG** [comment]
> Go to Settings - Network - Cookies, tap on the three dots icon on the top right and turn off `User agent` should work. The bug which causes this option to be enabled by accident was addressed in v1.11.2

Excuse me, but it seems like I'm facing the same problem. That is, after the following steps I'm still unable to download videos in a resolution of 1080p (which is available for my account):
1. click "Generate new cookies" which displays me a popup
2. input "https://www.bilibili.com" in the popup
3. click "Generaete new cookies" in the popup which leads me to the webpage
4. login my account
5. click "Done" button in the up-right corner and then click "Confirm" button in the popup
6. (following your instructions) turn off the "User agent" switch
I'm using the latest version of Seal (currently 1.12.1).

Does that means I still have to _use a cookies.txt dumped from browser on your PC_ ? If so, how can I do that?

Besides, in Settings-Network-Cookies page, It says I have "0 cookies from 0 websites in total". Does that mean cookie generation failed?

**Comment by JunkFood02** [comment]
> It says I have "0 cookies from 0 websites in total". Does that mean cookie generation failed?

Yes

**Comment by PYUDNG** [comment]
Thanks for your quick reply. I also tried to log in to youtube and still have 0 cookies from 0 websites in total. Is there anything I'm doing wrong, or is it a bug?

**Comment by PYUDNG** [comment]
Okay, thank you very much for your explanation. I've just tries cookies.txt and it worked like a charm:)
