### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by anuraag488** [JunkFood02/Seal#379]
### Describe the bug

Getting `Unexpected JSON token at offset 854781: Expected quotation mark '"', but had '3' instead at path: $.channel_id
JSON input: .....l": "StarPlus", "channel_id": 3, "series": "Anupama", "seaso.....` while downloading from hotstar.com but it works fine on yt-dlp.

### To Reproduce

Try downloading from https://www.hotstar.com/in/tv/anupama/1260022017/dimple-tries-to-escape/1000281382

### Error reports & Screenshots

![Screenshot_20221202-022909_Seal](https://user-images.githubusercontent.com/7353086/205158267-d0ae23fa-383a-46ff-8480-eba5438e6ab5.png)

### Device info

App version: 1.6.0 (10600)
Device information: Android 12 (API 32)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2164 x 1078

**Comment by JunkFood02** [comment]
Fixed in v1.7.0-beta.2

**Comment by anuraag488** [comment]
Working.

**Comment by heddxh** [comment]
v1.7.0-beta.2 still not works for me
My link: https://youtu.be/zlRRdGnzA00
Output: Unexpected JSON token at offset 69436: Failed to parse int for input '2793622092' at path: $.filesize_approx JSON input: ..... "filesize_approx": 2793622092, "tbr": 2983.8680000000004, ".....

**Comment by JunkFood02** [comment]
@heddxh done

**Comment by heddxh** [comment]
@JunkFood02 Working, thx!
