### ISSUE TITLE
[Bug Report] Parsing video size

### ISSUE THREAD

**Issue by hunkyburrito** [JunkFood02/Seal#975]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Trying to download with Seal gives a parsing error but downloading with a custom command or yt-dlp works as expected.

### To Reproduce

Try to download something from [redgifs. (NSFW)](https://redgifs.com) 

### Error reports

```
URL: https://www.redgifs.com/watch/bitesizedbigheartedconch
Unexpected JSON token at offset 676: Unexpected symbol '.' in numeric literal at path: $.formats[0].width
JSON input: ....., "format_id": "sd", "width": 202.5, "height": 360, "quality.....
```

### Device info

App version: 1.9.2 (10920)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

**Comment by JunkFood02** [comment]
should be fixed in v1.10.0-beta.4

**Comment by hunkyburrito** [comment]
Tested it and I'm still getting the same error but in another place:

```
App version: 1.10.0-beta.4 (10920)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

URL: https://www.redgifs.com/watch/femalepapayawhipbluegill#rel=tag%3Asfw%2Ca
Unexpected JSON token at offset 2602: Unexpected symbol '.' in numeric literal at path: $.width
JSON input: ....., "format_id": "hd", "width": 607.5, "height": 1080, "qualit.....
```

**Comment by JunkFood02** [comment]
I see, you can use custom commands to download it before the issue get resolved
